language: php

php:
  - 7.4snapshot

# Shallow clones can cause issues with subtree splits
git:
  depth: false

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script:
  - vendor/bin/phpunit --verbose
  #- composer run-script lint-check

deploy:
  # Push updates to the subtrees on commits to master
  - provider: script
    script: bash bin/split.sh $TRAVIS_BRANCH $GIT_USER $GIT_ACCESS_TOKEN
    on:
      branch: temp

notifications:
  email:
    - dave@aphiria.com

sudo: false

matrix:
  fast_finish: true
