language: php

php:
  - 7.4

# Shallow clones can cause issues with subtree splits
git:
  depth: false

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script:
  - vendor/bin/phpunit --verbose
  - composer run-script lint-check

deploy:
  - provider: script
    script: bash bin/split.sh $TRAVIS_BRANCH $GIT_USER $GIT_ACCESS_TOKEN $TRAVIS_TAG
    on:
      branch: master
    skip_cleanup: true

notifications:
  email:
    - dave@aphiria.com

sudo: false

matrix:
  fast_finish: true
